### ISSUE TITLE
Could you please add explanation of the output file

### ISSUE THREAD

**Issue by zhldestiny** [psipred/DeepMetaPSICOV#1]
The output file eg.1guuA.deepmetapsicov.con  1guuA.deepmetapsicov.map 1guuA.deepmetapsicov.21c  1guuA.deepmetapsicov.fix, could you please add some explanation about them.

**Comment by shaunmk** [comment]
Thanks for bringing this to our attention; I have now added a description of the outputs in the README. The `.21c`, `.fix` and `.map` files are not really outputs; they are the files that are read by the actual ResNet code to make predictions, and consist of the outputs from the various feature generation programs, but formatted correctly.
