### ISSUE TITLE
cannot find "makemat"

### ISSUE THREAD

**Issue by GiancarloCroce** [psipred/DeepMetaPSICOV#2]
Hi,
I would like to install your software, but I cannot find anywhere the "makemat" executable. I could not find it in the blast (v. 2.2.26) ftp repository (https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.26/).
Am I missing something?

Thank you

**Comment by shaunmk** [comment]
Hi,

makemat (and blastpgp and formatdb) can be found in the legacy BLAST package (not BLAST+). It can be found at https://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/2.2.26/

I'll update the README to include this link.
