### ISSUE TITLE
About contact potential

### ISSUE THREAD

**Issue by DaMaoShan** [psipred/DeepMetaPSICOV#3]
In _DeepMetaPSICOV/src/alnstats.c_
line 29, there is a definition of contact potential matrix, I have two questions:
0. What is the meaning of negative value?  
1. why column 16 all zeros?

Thank you very much!

**Comment by shaunmk** [comment]
The matrix is taken from Table 2 of [Betancourt and Thirumalai (1999)](https://doi.org/10.1110/ps.8.2.361). Only the upper triangle of values is used and converted into a symmetric matrix. The amino acids are in a different order as compared to this paper, but the values are the same. The order of amino acids in the alnstats version is given by the variable `rescodes`.
To answer your questions:

0. When creating potential functions, the convention is that negative values of the potential (or energy) function are favourable, and positive values are unfavourable. This is why interactions between hydrophobic amino acid pairs in the table have strong negative values, for example.
1. Column (and row) 16 corresponds to Threonine, which is used as a "reference" amino acid for the potential calculation; see the paper above for full details.

**Comment by DaMaoShan** [comment]
grateful for your detailed reply!
